### ISSUE TITLE
Works intermittently. Struggling with consistency.

### ISSUE THREAD

**Issue by bluefire2121** [HiraokaHyperTools/DeCompressRTF#1]
Hey @kenjiuno ,
I'm using this and your msgreader library. 
I've been struggling to get the decompression to work consistently. Sometimes it works and sometimes it doesn't. I've really large complicated emails where the decompression works perfectly. At other times, I've had small one liner emails where it doesn't work.

When it breaks, it only returns 

`{\rtf1\ansi\ansicpg1252\fromhtml1 \fbidis \deff0{\fonttbl
{\f0\fswiss\fchars`

Is it due to certain fonts being used? I can't seem to figure it out. Appreciate any insight and help you can give. 

I'm running:

`    const inputArray = msgInfo.compressedRtf as Uint8Array;
            const outputArray = decompressRTF(inputArray);
            const rtf = Buffer.from(outputArray).toString("ascii");
`

**Comment by kenjiuno** [comment]
@bluefire2121 hi thanks for reporting.
In order to reproduce, could you provide that `.msg` file? if it is not confidential contents.

**Comment by bluefire2121** [comment]
Thanks for replying @kenjiuno. In the example email, I had one line. All that was in the email was 

`Hello World`

**Comment by kenjiuno** [comment]
Ok, I have verified that this is **msgreader**'s problem. I'll try to fix it.

FYI `.msg` file is a generic [Compound File Binary Format](https://en.wikipedia.org/wiki/Compound_File_Binary_Format) can be accessed via [StgOpenStorage](https://docs.microsoft.com/en-us/windows/win32/api/coml2api/nf-coml2api-stgopenstorage) Win32 API. Today we can use [7-Zip](https://www.7-zip.org/) to extract files in it.

**Comment by kenjiuno** [comment]
I have fixed the problem https://github.com/HiraokaHyperTools/msgreader/commit/0a29badf28d820be53fc8baf86ff1f427e02aa62
And then published 1.2.6 https://www.npmjs.com/package/@kenjiuno/msgreader

**Comment by bluefire2121** [comment]
Thank you so much! It's working great now. I appreciate the quick response.
